- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: "140hrs"
    TRAINER: "shivakumar reddy"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "course is: {{ COURSE }}, trainer is: {{ TRAINER }}, Duration is: {{ DURATION }}"