- name: play level variables
  hosts: local
  connection: local
  vars_file:
  - course.yaml
  tasks:
  - name: print variables
    vars:
        COURSE: "ansible"
    ansible.builtin.debug:
      msg: "course is: {{ COURSE }}, trainer is: {{ TRAINER }}, Duration is: {{ DURATION }}"