- name: demo on conditions
  hosts: local
  connection: local
  vars:
    IS_LIVE: false
  tasks:
  - name: "check live or not"
    ansible.builtin.debug:
      msg: "yes, it is live"
    when: IS_LIVE #if when expression is true then only it runs if not it doenot runs