- name: demo on conditions
  hosts: local
  connection: local
  vars: 
    NUMBER_OF_SESSIONS: 7
  tasks:
  - name: is ansible more than 5  sessions
    ansible.builtin.debug:
       msg: "number of sessions is 5"
    when: NUMBER_OF_SESSIONS > 5