- name: installing packages
  hosts: local
  connection: local
  tasks:
  - name: instal packages
    ansible.builtin.package:
       name: "{{ item }}"
       state: present
    loop:
    - mysql
    - nginx
    - zip 
